[package]
name = "vimspell"
version = "0.1.0"
edition = "2024"
authors = ["Thomas Dagenais <exrok@i64.dev>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/exrok/vimspell"
description = "Native Rust library for spellchecking based on vimspell database and algorthim."
keywords = ["spellcheck", "spelling", "vim"]
categories = ["algorithms", "text-processing"]
rust-version = "1.90"
exclude = ["dicts/", "bench/", "devsm.toml"]

[dependencies]
hashbrown = { version = "0.16.1", default-features = false, features = [
    "inline-more",
    "default-hasher",
] }
